import type { Metadata } from 'next';
import { Source_Serif_4, Inter, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { Sidebar } from './components/Sidebar';
import Image from 'next/image';

const serif = Source_Serif_4({
  subsets: ['latin'],
  variable: '--font-serif',
  display: 'swap',
});

const sans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const mono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Keploy Documentation',
  description: 'Generated by Antigravity',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${serif.variable} ${sans.variable} ${mono.variable} antialiased scroll-smooth`}>
      <body className="bg-white text-zinc-900 min-h-screen flex flex-col font-sans">
        <header className="sticky top-0 z-50 w-full border-b border-zinc-200 bg-white">
          <div className="mx-auto flex h-16 w-full items-center justify-between px-6">
            <div className="flex items-center gap-2">
              <Image src="/images/keploylogo.svg" alt="Keploy Logo" width={120} height={32} />
            </div>
            <div className="hidden items-center gap-4 text-sm text-zinc-500 sm:flex font-sans">
              <span>Read Time: 5 min</span>
              <button className="rounded-full bg-zinc-900 px-4 py-1.5 text-xs font-semibold text-white transition-colors hover:bg-zinc-700">
                Follow
              </button>
            </div>
          </div>
        </header>

        <main className="flex-1 w-full px-6">
          <div className="flex gap-12 py-10 lg:py-12">
            <Sidebar />
            <article className="flex-1 min-w-0 prose prose-zinc prose-lg prose-headings:font-sans prose-code:font-mono prose-pre:bg-transparent prose-pre:p-0 prose-pre:m-0">
              {children}
            </article>
          </div>
        </main>
      </body>
    </html>
  );
}
