import { Inter } from 'next/font/google';
import './globals.css';
import { Sidebar } from './components/Sidebar';
import { ThemeToggle } from './components/ThemeToggle';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Keploy Documentation',
  description: 'Generated by Antigravity',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 z-50 bg-[var(--bg)] border-b border-[var(--border)] backdrop-blur">
          <div className="max-w-[1280px] mx-auto px-6 h-16 flex justify-between items-center">
            <div>
              <Image src="/images/keploylogo.svg" alt="Keploy Logo" width={120} height={32} />
            </div>
            <ThemeToggle />
          </div>
        </header>

        <main className="flex-1 w-full max-w-[1280px] mx-auto px-6 py-12 grid grid-cols-1 lg:grid-cols-[250px_1fr] gap-12">
          <div className="hidden lg:block">
            <Sidebar />
          </div>

          <article className="max-w-[65ch] flex-1 min-w-0 prose prose-zinc prose-lg prose-headings:font-sans prose-code:font-mono prose-pre:bg-transparent prose-pre:p-0">
            {children}
          </article>
        </main>

        <footer className="border-t border-[var(--border)] px-6 py-8 text-center text-[var(--text)] opacity-70">
          <p>Automated API Testing Made Simple.</p>
        </footer>
      </body>
    </html>
  );
}